### ISSUE TITLE
RSS内容有点少。

### ISSUE THREAD

**Issue by jiegec** [Liu233w/liu233w.github.io#2]
我打开RSS阅读器看到一片空白。。体验很不好

**Comment by Liu233w** [comment]
ego默认是在rss中只显示前5篇文章，等会我看看能不能改一下设置吧

发自我的 iPhone

在 2017年1月8日，下午10:48，Jiajie Chen <notifications@github.com<mailto:notifications@github.com>> 写道：


我打开RSS阅读器看到一片空白。。体验很不好

―

**Comment by Liu233w** [comment]
改成 50 条了，这样还行吧(´･ω･`)

**Comment by jiegec** [comment]
50 条是 50 条，但我想要的不是这个数量，而是把文章内容嵌入到RSS中去啊。。

**Comment by Liu233w** [comment]
这个意思啊_(:3」∠)_
